-- =============================================================================
-- METROPULSE — STATISTICAL ANALYSIS MART
-- =============================================================================
-- Grain:
--   One row per canonical hour after lag construction.
--
-- Purpose:
--   Authoritative regression dataset.
--
-- Note:
--   Statistical coefficients are generated by the regression analysis script,
--   not fabricated inside SQL.
-- =============================================================================

CREATE OR REPLACE TABLE marts.statistical_analysis AS

WITH base AS (

    SELECT

        pickup_hour,

        calendar_date,

        hour_of_day,

        day_of_week,

        is_weekend,

        month_start,

        taxi_trip_count,

        taxi_revenue,

        taxi_distance,

        taxi_duration_seconds,

        subway_ridership,

        subway_transfers,

        temperature_2m,

        relative_humidity_2m,

        precipitation,

        rain,

        wind_speed_10m,

        cloud_cover

    FROM marts.hourly_mobility_summary

),

lagged AS (

    SELECT

        *,

        LAG(taxi_trip_count, 1)
            OVER (
                ORDER BY pickup_hour
            ) AS taxi_trip_count_lag_1,

        LAG(taxi_trip_count, 2)
            OVER (
                ORDER BY pickup_hour
            ) AS taxi_trip_count_lag_2,

        LAG(taxi_trip_count, 24)
            OVER (
                ORDER BY pickup_hour
            ) AS taxi_trip_count_lag_24,

        LAG(taxi_trip_count, 168)
            OVER (
                ORDER BY pickup_hour
            ) AS taxi_trip_count_lag_168,

        LAG(subway_ridership, 1)
            OVER (
                ORDER BY pickup_hour
            ) AS subway_ridership_lag_1,

        LAG(subway_ridership, 2)
            OVER (
                ORDER BY pickup_hour
            ) AS subway_ridership_lag_2,

        LAG(subway_ridership, 24)
            OVER (
                ORDER BY pickup_hour
            ) AS subway_ridership_lag_24

    FROM base

)

SELECT

    *,

    EXTRACT(
        DOW FROM calendar_date
    ) AS regression_day_of_week,

    EXTRACT(
        MONTH FROM calendar_date
    ) AS regression_month,

    CASE
        WHEN precipitation > 0
        THEN 1
        ELSE 0
    END AS rain_flag

FROM lagged;